name: Patty container release

on:
  push:
    branches: [forge]
  workflow_dispatch: {}

jobs:
  release:
    uses: patty-io/.github/.github/workflows/container-release.yml@9f4d7ff0ab889b6a9db975331cb93cfd4d521d9c
    with:
      images: >-
        [{"image":"registry.patty.io/replace-me/app","context":".","dockerfile":"Dockerfile","title":"Replace Me"}]
    secrets:
      registry_username: ${{ secrets.REGISTRY_USER }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
