name: Patty container release

on:
  push:
    branches: [forge]
  workflow_dispatch: {}

jobs:
  release:
    uses: patty-io/.github/.github/workflows/container-release.yml@3a57bcb3717b7645804d468260932158f5e7a29b
    with:
      images: >-
        [{"image":"registry.patty.io/replace-me/app","context":".","dockerfile":"Dockerfile","title":"Replace Me"}]
    secrets:
      registry_username: ${{ secrets.REGISTRY_USER }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
